name: Pull Request Review

on:
  pull_request:
    types: [opened, edited]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ChatGPT review
        uses: khan/chatgpt@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ github.event.pull_request.head.repo.full_name }}
          number: ${{ github.event.pull_request.number }}
