name: Pull Request Review
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
         with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Review pull request
        run: npm run review
